name: campers_item
description: A Flutter application for managing camping items.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  floating_search_bar: ^0.3.0
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: "icon/icon.png" 
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
